<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TckImageResizer\Module'                                                                                => __DIR__ . '/Module.php',
    'TckImageResizer\Controller\IndexController'                                                            => __DIR__ . '/src/TckImageResizer/Controller/IndexController.php',
    'TckImageResizer\Controller\IndexControllerFactory'                                                     => __DIR__ . '/src/TckImageResizer/Controller/IndexControllerFactory.php',
    'TckImageResizer\Exception\BadMethodCallException'                                                      => __DIR__ . '/src/TckImageResizer/Exception/BadMethodCallException.php',
    'TckImageResizer\Service\CommandRegistry'                                                               => __DIR__ . '/src/TckImageResizer/Service/CommandRegistry.php',
    'TckImageResizer\Service\ImageProcessing'                                                               => __DIR__ . '/src/TckImageResizer/Service/ImageProcessing.php',
    'TckImageResizer\Service\ImageProcessingFactory'                                                        => __DIR__ . '/src/TckImageResizer/Service/ImageProcessingFactory.php',
    'TckImageResizer\Util\UrlSafeBase64'                                                                    => __DIR__ . '/src/TckImageResizer/Util/UrlSafeBase64.php',
    'TckImageResizer\View\Helper\Resize'                                                                    => __DIR__ . '/src/TckImageResizer/View/Helper/Resize.php',
);
